[package]
name = "webscreen"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1"
log = "0.4.19"
actix-web = "4"
env_logger = "0.10.0"
headless_chrome = "1.0.5"
clap = { version = "4.2.0", features = ["derive"] }