on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: cargo install -f cross

      - name: Version
        shell: bash
        env:
          RELEASE_TAG: ${{ github.ref }}
        run: |
          sed -i "s/0\\.0\\.0-git/${RELEASE_TAG##*\/v}/" Cargo.toml
          sed -i "s/0\\.0\\.0-git/${RELEASE_TAG##*\/v}/" Cargo.lock

      - name: Build-linux
        run: cross build --target x86_64-unknown-linux-gnu --release

      - name: Build-win
        run: cross build --target x86_64-pc-windows-gnu --release

      - name: Package Linux
        run: tar -czvf webscreen-linux-x86_64.tar.gz -C target/x86_64-unknown-linux-gnu/release/ webscreen

      - name: Package Windows
        run: zip webscreen-windows-x86_64.zip target/x86_64-pc-windows-gnu/release/webscreen.exe

      - name: Publish
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: webscreen-linux-x86_64.tar.gz,webscreen-windows-x86_64.zip
          token: ${{ secrets.GITHUB_TOKEN }}
