name: Rust App Build

on:
  push:
    branches:
      - main

jobs:
  compile-linux:
    name: Compile for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Linux executable
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Archive executable
        run: tar -czvf webscreen-linux.tar.gz target/x86_64-unknown-linux-gnu/release/webscreen

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: webscreen-linux
          path: webscreen-linux.tar.gz

  compile-windows:
    name: Compile for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Windows executable
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Archive executable
        run: 7z a webscreen-windows.zip target/x86_64-pc-windows-gnu/release/webscreen.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: webscreen-windows
          path: webscreen-windows.zip

  compile-darwin:
    name: Compile for Darwin (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build macOS executable
        run: cargo build --release --target x86_64-apple-darwin

      - name: Archive executable
        run: zip -r webscreen-darwin.zip target/x86_64-apple-darwin/release/webscreen

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: webscreen-darwin
          path: webscreen-darwin.zip
